volumes:
  postgres:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data:cached

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 5s


